# docker-Spécification de la version de composition
version: "3"

services:
#redis
  redis:
  #Image redis du Docker Hub
    image: redis
    container_name: cache
    ports:
      - "3030:3030"
    #expose:
     # - 6379

  app:
    #Construction du Dockerfile dans le même répertoire
    build: .
    #Montage des fichiers du répertoire dans le répertoire de l'application dans le conteneur
    volumes: 
      - .:/app
    #Montage du port 8080 du côté du conteneur sur le port 8080 du côté de l'hôte.
    ports:
      - "8080:8080"
    #Liaison à redis
    links:
      - redis
    #Définition de l'environnement
    environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=8080
    #Dépendance
    depends_on:
      - redis